AWSTemplateFormatVersion: "2010-09-09"
Description: Template for NAT gateway to allow EC2 access using session manager. It depends on the vpc stack.

Parameters:
  StackPrefix:
    Description: Unique Prefix to associate with the resources
    Type: String

Resources:
  EIP1:
    Type: AWS::EC2::EIP

  EIP2:
    Type: AWS::EC2::EIP

  NATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP1.AllocationId
      SubnetId: { Fn::ImportValue: !Join ["-", [!Ref StackPrefix, PubSub1A]] }

  NATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP2.AllocationId
      SubnetId: { Fn::ImportValue: !Join ["-", [!Ref StackPrefix, PubSub1B]] }

  NATGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        { Fn::ImportValue: !Join ["-", [!Ref StackPrefix, PrivRouteTable]] }
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1
